name: "Setup Dependencies"
description: "Installs dependencies for the project"

inputs:
  dev-dependencies:
    description: "Install development dependencies"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry==2.0.0
    - name: Install Python 3.13 with Poetry Cache
      uses: actions/setup-python@v5.3.0
      with:
        python-version-file: "pyproject.toml"
        cache: "poetry"
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install Poetry Dependencies
      if: ${{ inputs.dev-dependencies == 'false' }}
      shell: bash
      run: just install
    - name: Install Poetry Dev Dependencies
      if: ${{ inputs.dev-dependencies == 'true' }}
      shell: bash
      run: just install
