name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: 30 1 * * 0

permissions:
  contents: read
  packages: read
  statuses: write
  security-events: write

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      # Lint and Format everything but Python
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LINTER_RULES_PATH: .github/super-linter-configurations
          YAML_ERROR_ON_WARNING: true
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_PYINK: false

  check-python-code-format-and-quality:
    name: Check Python Code Format and Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python Dependencies
        uses: ./.github/actions/setup-python-dependencies

      - name: Check Python Code for Dead Code (Vulture)
        run: just detector::vulture

      - name: Check Python Code Format (Ruff)
        run: just ruff-format
        env:
          RUFF_OUTPUT_FORMAT: "github"

      - name: Check Python Code Quality (Ruff)
        run: just ruff-lint
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.27.0
        with:
          sarif_file: ruff-results.sarif
          wait-for-processing: true


  run-codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.27.0
        with:
          languages: python
          queries: security-and-quality
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.27.0
